### ISSUE TITLE
CORS should be considered

### ISSUE THREAD

**Issue by HeSe** [sebastianconcept/Mapless#2]
Right now Mapless uses jQuery ajax calls. This makes development a little tricky when amber node server and the backend are running on different IPs.

**Comment by sebastianconcept** [comment]
This repo is not maintained @HeSe 
Please use this one instead:
http://github.com/flow-stack/Mapless

Regarding to your question the cross-domain issue is currently handled by the right nginx configuration that can easily route traffic to any IP you set. Isn't that enough?

**Comment by HeSe** [comment]
One can not post issues in forked projects

I won't use nginx on my Gemstone configuration. We should find a more general solution, but if it works with nginx, than that should definitely tried out.

**Comment by dalehenrich** [comment]
@HeSe actually you can create issues for forked projects. There's a checkbox on the project settings menu to enable issues ...

**Comment by HeSe** [comment]
@dalehenrich @sebastianconcept I am not maintainer of flow-stack/Mapless,... I can't.

**Comment by sebastianconcept** [comment]
That's the protip I was waiting for! Thanks  @dalehenrich 

I'm enabling issues in all /flow-stack/  repos

**Comment by sebastianconcept** [comment]
BTW you guys were invited to the flow-stack organization on GitHub as contributors so you could send PRs and review merge too.

**Comment by eMaringolo** [comment]
CORS has nothing to do with Mapless. Should we close this?

**Comment by sebastianconcept** [comment]
Yes @eMaringolo that was very creative. Closing...
