### ISSUE TITLE
Add Resolver for MaplessReference

### ISSUE THREAD

**Issue by eMaringolo** [sebastianconcept/Mapless#22]
Currently a `MaplessReference` will instantiate the referenced object, regardless of whether such reference was instatiated before in the same repository, producing multiple instances of the same "logical" object.

A `MaplessResference` should have `Resolver` (reference resolver), probably defined in the `MaplessRepository`, then the reference will go through the resolver, the default resolver will preserve the current behavior to provide backwards compatibility (and simplicity), but we could introduce a `CacheResolver` that will first look into a cache before going to the database to fetch the object from the collection.

**Comment by sebastianconcept** [comment]
@eMaringolo I like the idea of leaving room to plug different strategies to do that. And yes, at this point it will create proxies to references but only query for its document lazily with the DNU when they receive some message.

If we add a `MaplessReferenceResolver` I'm thinking in two questions:
1. The model identity and
2. the proxied model identity

Whatever it is going to do, it has to maintain that consistent in one cache.

One approach I think is to use the dynamic variable `MaplessCurrentRepository` to hold the lifespan of that cached object in a way that can be thread safe without requiring further complexity. If we use that, the name of that dynamic variable might change to something that isn't a transaction but starts to feel like one.

If you have suggestions, feedback or further input to consider I'd like to hear.

**Comment by sebastianconcept** [comment]
Done here https://github.com/sebastianconcept/Mapless/pull/48

Thanks again @eMaringolo
